version: "3.8"
services:
  torch-serve:
    image: torch_serve:latest
    ports:
      - 9080:8080
      - 9081:8081
      - 9082:8082
    volumes:
      - ./src/logs:/home/model-server/logs
    
    restart: always
