version: "3.8"
services:
  torch-serve-pill:
    container_name: torch-serve-pill
    image: torch_serve_pill:latest
    ports:
      - 8280:8080
      - 8281:8081
      - 8282:8082
    volumes:
      - ./src/logs:/home/model-server/logs
    
    restart: always
